### ISSUE TITLE
Ajout d'un ReadMe

### ISSUE THREAD

**Issue by Kohorne** [Barbebizarre/Project_Git#7]
**Pouvez-vous ajouter la fonctionnalité : Créer un readme efficient pour le projet**

Mon problème est (claire et consci) : le projet n'est pas claire 

Je voudrais qu'elle fonctionne comme ceci (claire et consci) : partie installation, utilisation, contribution et licence

Autre :

**Comment by Barbebizarre** [comment]
demande traiter et merger comme ceci  : 
https://github.com/Barbebizarre/Project_Git/pull/8
